
cost_grid:
  depth:
    time: 6 # discrete time steps
    x: 6 # no. of deltas for length
    y: 5 # no. of deltas for width
  delta:
    time: 1 #[s]
    x: 0.2 #[m]
    y: 0.1 #[m]

velocity:
  max: 0.225s #[m/s] (must be >= max(dy/dt, dx/dt))
